spring:
  datasource:
    url: jdbc:h2:file:~/ShopAppDatabase1
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enable: false
      path: /h2
      settings:
        trace: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
