spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ShopAppDatabase
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

