INSERT INTO "PUBLIC"."PRODUCTS" VALUES(1, 3.0, 'milk');
INSERT INTO "PUBLIC"."PRODUCTS" VALUES(2, 5.0, 'butter');     
INSERT INTO "PUBLIC"."PRODUCTS" VALUES(3, 4.5, 'pasta');      
INSERT INTO "PUBLIC"."PRODUCTS" VALUES(4, 1.5, 'yogurt');     
INSERT INTO "PUBLIC"."PRODUCTS" VALUES(5, 5.5, 'lettuce');    
