CREATE Schema "SHOPAPPDATABASE.MV";


CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B1A44CC2_FE78_464A_998D_FBA6A4C47F1B" START WITH 6 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A4B30D6F_098A_4231_88B5_D35CEC78D4AE" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_31463346_7BDA_4354_94DC_64A7D2E5DD1C" START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE "PUBLIC"."CLIENTS"(
                                          "CLIENT_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_31463346_7BDA_4354_94DC_64A7D2E5DD1C" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_31463346_7BDA_4354_94DC_64A7D2E5DD1C",
                                          "CITY" VARCHAR(255),
                                          "COUNTRY" VARCHAR(255),
                                          "FIRST_NAME" VARCHAR(255),
                                          "LAST_NAME" VARCHAR(255),
                                          "POSTAL_CODE" VARCHAR(255),
                                          "STREET" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."CLIENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("CLIENT_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLIENTS;
CREATE CACHED TABLE "PUBLIC"."CLIENTS_CLIENT_ORDERS"(
                                                        "CLIENT_CLIENT_ID" BIGINT NOT NULL,
                                                        "CLIENT_ORDERS_ORDER_ID" BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLIENTS_CLIENT_ORDERS;
CREATE CACHED TABLE "PUBLIC"."ORDERS"(
                                         "ORDER_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_A4B30D6F_098A_4231_88B5_D35CEC78D4AE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A4B30D6F_098A_4231_88B5_D35CEC78D4AE",
                                         "CLIENT_CLIENT_ID" BIGINT
);
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ORDER_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;
CREATE CACHED TABLE "PUBLIC"."PRODUCT_ORDER"(
                                                "PRODUCT_ID" BIGINT NOT NULL,
                                                "ORDER_ID" BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_ORDER;
CREATE CACHED TABLE "PUBLIC"."PRODUCTS"(
                                           "PRODUCT_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_B1A44CC2_FE78_464A_998D_FBA6A4C47F1B" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B1A44CC2_FE78_464A_998D_FBA6A4C47F1B",
                                           "PRICE" DOUBLE,
                                           "PRODUCT_NAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."PRODUCTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("PRODUCT_ID");
ALTER TABLE "PUBLIC"."CLIENTS_CLIENT_ORDERS" ADD CONSTRAINT "PUBLIC"."UK_92XIGW8DWNI49RS92VBG75C8A" UNIQUE("CLIENT_ORDERS_ORDER_ID");
ALTER TABLE "PUBLIC"."CLIENTS_CLIENT_ORDERS" ADD CONSTRAINT "PUBLIC"."FKK6OBK1D8KP9GPY598LQD6590J" FOREIGN KEY("CLIENT_CLIENT_ID") REFERENCES "PUBLIC"."CLIENTS"("CLIENT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCT_ORDER" ADD CONSTRAINT "PUBLIC"."FK26K4LFWLU930G8BX6EKL99UFJ" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."PRODUCTS"("PRODUCT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCT_ORDER" ADD CONSTRAINT "PUBLIC"."FKHJ126CTC1PUTQDJXIW9TJK47W" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."ORDERS"("ORDER_ID") NOCHECK;
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FKCM7TTU9365NYYV400U3WOJRFV" FOREIGN KEY("CLIENT_CLIENT_ID") REFERENCES "PUBLIC"."CLIENTS"("CLIENT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."CLIENTS_CLIENT_ORDERS" ADD CONSTRAINT "PUBLIC"."FKRBOTA9N6WLESQ38T6ABAOVP3X" FOREIGN KEY("CLIENT_ORDERS_ORDER_ID") REFERENCES "PUBLIC"."ORDERS"("ORDER_ID") NOCHECK;
